name       : haskell-text-metrics
version    : 0.2.0
release    : 1
source     :
    - http://hackage.haskell.org/package/text-metrics-0.2.0/text-metrics-0.2.0.tar.gz : 082304ce14ac6182cbb93f51207d90b91d104e5d1fc1b17bbe1c9280ebffe43a
license    : BSD-3-Clause
component  : programming.haskell
summary    : Calculate various string metrics efficiently.
description: |
    Calculate various string metrics efficiently.
builddeps  :
    - haskell-cabal-install
    - haskell-nats
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register