name       : haskell-text-metrics
version    : 0.3.0
release    : 2
source     :
    - https://hackage.haskell.org/package/text-metrics-0.3.0/text-metrics-0.3.0.tar.gz : 3874af74060e35f01702640b353ac2180d93bb5d292a204e0ee3cadd26efbfa2
license    : BSD-3-Clause
component  : programming.haskell
summary    : Calculate various string metrics efficiently.
description: |
    Calculate various string metrics efficiently.
builddeps  :
    - haskell-cabal-install
    - haskell-text
    - haskell-vector
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |-
    %cabal_install
    %cabal_register
